### ISSUE TITLE
Jerky horizontal movement of cards when a card is dismissed in gridview

### ISSUE THREAD

**Issue by saibbyweb** [brnunes/SwipeableRecyclerView#11]
When I am dismissing a card in single column Card-views, the other cards get sorted perfectly. But when I dismiss a card in multi-column view, the cards move abruptly (horizontally) ? 
Example : If there are two columns of cards (having a left card and a right card), if I dismiss the left card, the right card abruptly takes the place of the left card (no animation at all). However, if I dismiss the right card, the card below the dismissed card moves smoothly (vertically upwards) ? Any fixes on horizontal animation?

**Comment by brnunes** [comment]
The library was made with only a single column layout in mind. The animation would have to be fixed on the [performDismiss](https://github.com/brnunes/SwipeableRecyclerView/blob/master/lib/src/main/java/com/github/brnunes/swipeablerecyclerview/SwipeableRecyclerViewTouchListener.java#L292-L361) method.
If you do that, please make a pull request. If not, I'll work on it in the future.
Thanks for reporting.

**Comment by saibbyweb** [comment]
I have no idea how to fix this. Kindly, fix it yourself asap. Help would be appreciated.

**Comment by brnunes** [comment]
I'll close this as it's out of the scope of this library. Updated the README making it clear that this is a simple solution for a single column list. There are other well-maintained libraries that do much more, such as https://github.com/h6ah4i/android-advancedrecyclerview. Anyway, thanks for the feedback.
