### ISSUE TITLE
Publishing to Maven

### ISSUE THREAD

**Issue by benhylau** [brnunes/SwipeableRecyclerView#6]
Do you want to publish releases to Maven? I can make a PR to do that. If not just close this issue. Thanks!

**Comment by brnunes** [comment]
Sure, if you think that will be helpful to users.
Thanks for collaborating! :)

**Comment by benhylau** [comment]
Thanks! This is a very useful library I think many developers will benefit getting this through Maven.
PR -> https://github.com/brnunes/SwipeableRecyclerView/pull/7
