### ISSUE TITLE
minSdkVersion

### ISSUE THREAD

**Issue by benhylau** [brnunes/SwipeableRecyclerView#9]
Is it really? https://github.com/brnunes/SwipeableRecyclerView/blob/master/lib/build.gradle#L8
I need to `tools:overrideLibrary="com.github.brnunes.swipeablerecyclerview"` in my app.

**Comment by brnunes** [comment]
I updated to 12, because of the animations. Do you need to support earlier versions? I think NineOldAndroids could be used to improve support.
I uploaded a new version to the central repository and will update the instructions when it's online.

**Comment by benhylau** [comment]
Perfect, I just need 12. Thanks!
You may also want to consider tagging the releases :)

**Comment by brnunes** [comment]
Done!

**Comment by benhylau** [comment]
:+1: Thanks!
